Wurf: main.o vektorMethoden.o
	gcc -o Wurf main.o vektorMethoden.o -lm

main.o: main.c
	gcc -c -o main.o main.c -lm

vektorMethoden.o: vektorMethoden.c
	gcc -c -o vektorMethoden.o vektorMethoden.c -lm
